name: Jazzy CI

on:
  push:
    branches:
      - jazzy 
jobs:
  jazzy_source:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout jazzy branch
        uses: actions/checkout@v4
        with:
          ref: jazzy

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - run: |
          # Create the workspace and move the repository to src
          mkdir -p ~/ros2_ws/src
          mv $(ls -d * | grep -v ros2_ws) ~/ros2_ws/src
          cd ~/ros2_ws
          sudo rosdep init || true
          rosdep update

      - run: |
          cd ~/ros2_ws
          rosdep install --from-paths src -i -r -y

      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: easy_ur_control
          target-ros2-distro: jazzy
